apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-mysql-pod
spec:
  containers:
  - name: spring-boot
    image: yhc0818/politicia-core-service:latest
    ports:
    - containerPort: 8080
    env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://localhost:3306/politicia
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "1234"
    - name: MYSQL_DATABASE
      value: politicia
    ports:
    - containerPort: 3306
