apiVersion: v1
kind: Service
metadata:
  name: spring-boot-mysql-load-balancer
spec:
  selector:
    app: spring-boot-mysql
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: mysql
    port: 3306
    targetPort: 3306