apiVersion: v1
kind: Service
metadata:
  name: spring-boot-mysql-node-port
spec:
  selector:
    app: spring-boot-mysql
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30306